export const COUNTRIES = [
    { "id": "1", "name": "Afghanistan", "iso": "af" },
    { "id": "2", "name": "Albania", "iso": "al" },
    { "id": "3", "name": "Algeria", "iso": "dz" },
    { "id": "4", "name": "Andorra", "iso": "ad" },
    { "id": "5", "name": "Angola", "iso": "ao" },
    { "id": "6", "name": "Antigua and Barbuda", "iso": "ag" },
    { "id": "7", "name": "Argentina", "iso": "ar" },
    { "id": "8", "name": "Armenia", "iso": "am" },
    { "id": "9", "name": "Australia", "iso": "au" },
    { "id": "10", "name": "Austria", "iso": "at" },
    { "id": "11", "name": "Azerbaijan", "iso": "az" },
    { "id": "12", "name": "Bahamas", "iso": "bs" },
    { "id": "13", "name": "Bahrain", "iso": "bh" },
    { "id": "14", "name": "Bangladesh", "iso": "bd" },
    { "id": "15", "name": "Barbados", "iso": "bb" },
    { "id": "16", "name": "Belarus", "iso": "by" },
    { "id": "17", "name": "Belgium", "iso": "be" },
    { "id": "18", "name": "Belize", "iso": "bz" },
    { "id": "19", "name": "Benin", "iso": "bj" },
    { "id": "20", "name": "Bhutan", "iso": "bt" },
    { "id": "21", "name": "Bolivia", "iso": "bo" },
    { "id": "22", "name": "Bosnia and Herzegovina", "iso": "ba" },
    { "id": "23", "name": "Botswana", "iso": "bw" },
    { "id": "24", "name": "Brazil", "iso": "br" },
    { "id": "25", "name": "Brunei", "iso": "bn" },
    { "id": "26", "name": "Bulgaria", "iso": "bg" },
    { "id": "27", "name": "Burkina Faso", "iso": "bf" },
    { "id": "28", "name": "Burundi", "iso": "bi" },
    { "id": "29", "name": "Cape Verde", "iso": "cv" },
    { "id": "30", "name": "Cambodia", "iso": "kh" },
    { "id": "31", "name": "Cameroon", "iso": "cm" },
    { "id": "32", "name": "Canada", "iso": "ca" },
    { "id": "33", "name": "Central African Republic", "iso": "cf" },
    { "id": "34", "name": "Chad", "iso": "td" },
    { "id": "35", "name": "Chile", "iso": "cl" },
    { "id": "36", "name": "China", "iso": "cn" },
    { "id": "37", "name": "Colombia", "iso": "co" },
    { "id": "38", "name": "Comoros", "iso": "km" },
    { "id": "39", "name": "Congo (Brazzaville)", "iso": "cg" },
    { "id": "40", "name": "Congo (Kinshasa)", "iso": "cd" },
    { "id": "41", "name": "Costa Rica", "iso": "cr" },
    { "id": "42", "name": "Croatia", "iso": "hr" },
    { "id": "43", "name": "Cuba", "iso": "cu" },
    { "id": "44", "name": "Cyprus", "iso": "cy" },
    { "id": "45", "name": "Czech Republic", "iso": "cz" },
    { "id": "46", "name": "Denmark", "iso": "dk" },
    { "id": "47", "name": "Djibouti", "iso": "dj" },
    { "id": "48", "name": "Dominica", "iso": "dm" },
    { "id": "49", "name": "Dominican Republic", "iso": "do" },
    { "id": "50", "name": "Ecuador", "iso": "ec" },
    { "id": "51", "name": "Egypt", "iso": "eg" },
    { "id": "52", "name": "El Salvador", "iso": "sv" },
    { "id": "53", "name": "Equatorial Guinea", "iso": "gq" },
    { "id": "54", "name": "Eritrea", "iso": "er" },
    { "id": "55", "name": "Estonia", "iso": "ee" },
    { "id": "56", "name": "Ethiopia", "iso": "et" },
    { "id": "57", "name": "Fiji", "iso": "fj" },
    { "id": "58", "name": "Finland", "iso": "fi" },
    { "id": "59", "name": "France", "iso": "fr" },
    { "id": "60", "name": "Gabon", "iso": "ga" },
    { "id": "61", "name": "Gambia", "iso": "gm" },
    { "id": "62", "name": "Georgia", "iso": "ge" },
    { "id": "63", "name": "Germany", "iso": "de" },
    { "id": "64", "name": "Ghana", "iso": "gh" },
    { "id": "65", "name": "Greece", "iso": "gr" },
    { "id": "66", "name": "Grenada", "iso": "gd" },
    { "id": "67", "name": "Guatemala", "iso": "gt" },
    { "id": "68", "name": "Guinea", "iso": "gn" },
    { "id": "69", "name": "Guinea-Bissau", "iso": "gw" },
    { "id": "70", "name": "Guyana", "iso": "gy" },
    { "id": "71", "name": "Haiti", "iso": "ht" },
    { "id": "72", "name": "Honduras", "iso": "hn" },
    { "id": "73", "name": "Hungary", "iso": "hu" },
    { "id": "74", "name": "Iceland", "iso": "is" },
    { "id": "75", "name": "India", "iso": "in" },
    { "id": "76", "name": "Indonesia", "iso": "id" },
    { "id": "77", "name": "Iran", "iso": "ir" },
    { "id": "78", "name": "Iraq", "iso": "iq" },
    { "id": "79", "name": "Ireland", "iso": "ie" },
    { "id": "80", "name": "Israel", "iso": "il" },
    { "id": "81", "name": "Italy", "iso": "it" },
    { "id": "82", "name": "Jamaica", "iso": "jm" },
    { "id": "83", "name": "Japan", "iso": "jp" },
    { "id": "84", "name": "Jordan", "iso": "jo" },
    { "id": "85", "name": "Kazakhstan", "iso": "kz" },
    { "id": "86", "name": "Kenya", "iso": "ke" },
    { "id": "87", "name": "Kiribati", "iso": "ki" },
    { "id": "88", "name": "North Korea", "iso": "kp" },
    { "id": "89", "name": "South Korea", "iso": "kr" },
    { "id": "90", "name": "Kosovo", "iso": "xk" },
    { "id": "91", "name": "Kuwait", "iso": "kw" },
    { "id": "92", "name": "Kyrgyzstan", "iso": "kg" },
    { "id": "93", "name": "Laos", "iso": "la" },
    { "id": "94", "name": "Latvia", "iso": "lv" },
    { "id": "95", "name": "Lebanon", "iso": "lb" },
    { "id": "96", "name": "Lesotho", "iso": "ls" },
    { "id": "97", "name": "Liberia", "iso": "lr" },
    { "id": "98", "name": "Libya", "iso": "ly" },
    { "id": "99", "name": "Liechtenstein", "iso": "li" },
    { "id": "100", "name": "Lithuania", "iso": "lt" },
    { "id": "101", "name": "Luxembourg", "iso": "lu" },
    { "id": "102", "name": "North Macedonia", "iso": "mk" },
    { "id": "103", "name": "Madagascar", "iso": "mg" },
    { "id": "104", "name": "Malawi", "iso": "mw" },
    { "id": "105", "name": "Malaysia", "iso": "my" },
    { "id": "106", "name": "Maldives", "iso": "mv" },
    { "id": "107", "name": "Mali", "iso": "ml" },
    { "id": "108", "name": "Malta", "iso": "mt" },
    { "id": "109", "name": "Marshall Islands", "iso": "mh" },
    { "id": "110", "name": "Mauritania", "iso": "mr" },
    { "id": "111", "name": "Mauritius", "iso": "mu" },
    { "id": "112", "name": "Mexico", "iso": "mx" },
    { "id": "113", "name": "Micronesia", "iso": "fm" },
    { "id": "114", "name": "Moldova", "iso": "md" },
    { "id": "115", "name": "Monaco", "iso": "mc" },
    { "id": "116", "name": "Mongolia", "iso": "mn" },
    { "id": "117", "name": "Montenegro", "iso": "me" },
    { "id": "118", "name": "Morocco", "iso": "ma" },
    { "id": "119", "name": "Mozambique", "iso": "mz" },
    { "id": "120", "name": "Myanmar", "iso": "mm" },
    { "id": "121", "name": "Namibia", "iso": "na" },
    { "id": "122", "name": "Nauru", "iso": "nr" },
    { "id": "123", "name": "Nepal", "iso": "np" },
    { "id": "124", "name": "Netherlands", "iso": "nl" },
    { "id": "125", "name": "New Zealand", "iso": "nz" },
    { "id": "126", "name": "Nicaragua", "iso": "ni" },
    { "id": "127", "name": "Niger", "iso": "ne" },
    { "id": "128", "name": "Nigeria", "iso": "ng" },
    { "id": "129", "name": "Norway", "iso": "no" },
    { "id": "130", "name": "Oman", "iso": "om" },
    { "id": "131", "name": "Pakistan", "iso": "pk" },
    { "id": "132", "name": "Palau", "iso": "pw" },
    { "id": "133", "name": "Palestine", "iso": "ps" },
    { "id": "134", "name": "Panama", "iso": "pa" },
    { "id": "135", "name": "Papua New Guinea", "iso": "pg" },
    { "id": "136", "name": "Paraguay", "iso": "py" },
    { "id": "137", "name": "Peru", "iso": "pe" },
    { "id": "138", "name": "Philippines", "iso": "ph" },
    { "id": "139", "name": "Poland", "iso": "pl" },
    { "id": "140", "name": "Portugal", "iso": "pt" },
    { "id": "141", "name": "Qatar", "iso": "qa" },
    { "id": "142", "name": "Romania", "iso": "ro" },
    { "id": "143", "name": "Russia", "iso": "ru" },
    { "id": "144", "name": "Rwanda", "iso": "rw" },
    { "id": "145", "name": "Saint Kitts and Nevis", "iso": "kn" },
    { "id": "146", "name": "Saint Lucia", "iso": "lc" },
    { "id": "147", "name": "Saint Vincent and the Grenadines", "iso": "vc" },
    { "id": "148", "name": "Samoa", "iso": "ws" },
    { "id": "149", "name": "San Marino", "iso": "sm" },
    { "id": "150", "name": "Sao Tome and Principe", "iso": "st" },
    { "id": "151", "name": "Saudi Arabia", "iso": "sa" },
    { "id": "152", "name": "Senegal", "iso": "sn" },
    { "id": "153", "name": "Serbia", "iso": "rs" },
    { "id": "154", "name": "Seychelles", "iso": "sc" },
    { "id": "155", "name": "Sierra Leone", "iso": "sl" },
    { "id": "156", "name": "Singapore", "iso": "sg" },
    { "id": "157", "name": "Slovakia", "iso": "sk" },
    { "id": "158", "name": "Slovenia", "iso": "si" },
    { "id": "159", "name": "Solomon Islands", "iso": "sb" },
    { "id": "160", "name": "Somalia", "iso": "so" },
    { "id": "161", "name": "South Africa", "iso": "za" },
    { "id": "162", "name": "South Sudan", "iso": "ss" },
    { "id": "163", "name": "Spain", "iso": "es" },
    { "id": "164", "name": "Sri Lanka", "iso": "lk" },
    { "id": "165", "name": "Sudan", "iso": "sd" },
    { "id": "166", "name": "Suriname", "iso": "sr" },
    { "id": "167", "name": "Eswatini", "iso": "sz" },
    { "id": "168", "name": "Sweden", "iso": "se" },
    { "id": "169", "name": "Switzerland", "iso": "ch" },
    { "id": "170", "name": "Syria", "iso": "sy" },
    { "id": "171", "name": "Taiwan", "iso": "tw" },
    { "id": "172", "name": "Tajikistan", "iso": "tj" },
    { "id": "173", "name": "Tanzania", "iso": "tz" },
    { "id": "174", "name": "Thailand", "iso": "th" },
    { "id": "175", "name": "Timor-Leste", "iso": "tl" },
    { "id": "176", "name": "Togo", "iso": "tg" },
    { "id": "177", "name": "Tonga", "iso": "to" },
    { "id": "178", "name": "Trinidad and Tobago", "iso": "tt" },
    { "id": "179", "name": "Tunisia", "iso": "tn" },
    { "id": "180", "name": "Turkey", "iso": "tr" },
    { "id": "181", "name": "Turkmenistan", "iso": "tm" },
    { "id": "182", "name": "Tuvalu", "iso": "tv" },
    { "id": "183", "name": "Uganda", "iso": "ug" },
    { "id": "184", "name": "Ukraine", "iso": "ua" },
    { "id": "185", "name": "United Arab Emirates", "iso": "ae" },
    { "id": "186", "name": "United Kingdom", "iso": "gb" },
    { "id": "187", "name": "United States of America", "iso": "us" },
    { "id": "188", "name": "Uruguay", "iso": "uy" },
    { "id": "189", "name": "Uzbekistan", "iso": "uz" },
    { "id": "190", "name": "Vanuatu", "iso": "vu" },
    { "id": "191", "name": "Vatican City", "iso": "va" },
    { "id": "192", "name": "Venezuela", "iso": "ve" },
    { "id": "193", "name": "Vietnam", "iso": "vn" },
    { "id": "194", "name": "Yemen", "iso": "ye" },
    { "id": "195", "name": "Zambia", "iso": "zm" },
    { "id": "196", "name": "Zimbabwe", "iso": "zw" }
]

export const COUNTRY_NAMES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cape Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Brazzaville)",
    "Congo (Kinshasa)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "North Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Eswatini",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]